### PR TITLE
[ADD] Entering a Taxi should now automatically spawn a new random veh…

### PR DESCRIPTION
**Pull request by QuickNET-Tech**
Entering a Taxi should now automatically spawn a new random vehicle.

### CODE REVIEW

**Comment by isaackd** [comment]
Looks good! Just gotta test it with the under the bridge code I've just added, then I'll merge.

**Comment by QuickNET-Tech** [comment]
alright. also, might be better to change `if(ENTITY::GET_ENTITY_MODEL(PED::GET_VEHICLE_PED_IS_IN(PLAYER::PLAYER_PED_ID(), true)) == GAMEPLAY::GET_HASH_KEY("TAXI")) {`
to
`Ped myPed = PLAYER::PLAYER_PED_ID();`
`Vehicle veh = PED::GET_VEHICLE_PED_IS_IN(myPed, true);`
`if(ENTITY::GET_ENTITY_MODEL(veh) == GAMEPLAY::GET_HASH_KEY("TAXI") && VEHICLE::GET_PED_IN_VEHICLE_SEAT(veh, -1) == myPed) {`
if baron would prefer the taxi swap to only happen as driver and not as a passenger.

**Comment by isaackd** [comment]
Yeah, that sounds better. Did you want to update your branch or would you rather I merge this then add it myself?

**Comment by QuickNET-Tech** [comment]
Would probably be better if you add it yourself :D

**Pull request merged**
